### ISSUE TITLE
Dependency conflict with Langchain==3.3.3

### ISSUE THREAD

**Issue by mrbende** [odwyersoftware/mega.py#103]
Mega.py package requires tenacity <6.0.0 (specifically, it seems to work with 5.1.5)... This is no longer compatible with the recent deployments of Langchain, which requires tenacity version 8.1.0 or newer. This creates a conflict with many of my applications and I am forced to uninstall Mega.py because it requires an older version of tenacity.

Can this package be updated to use a more recent version of tenacity and be compatible with recent developments? Thanks!

**Comment by njikgg** [comment]
A bit late to answering this question but I suggest you just upgrade tenacity (`pip install --upgrade tenacity`). It also allows you to use it in python 3.12. When I worked on my project using the newer version of tenacity I haven't experienced any problems. I'm not quite sure if it _is_ really safe though.
