### ISSUE TITLE
unable to download a file

### ISSUE THREAD

**Issue by ACE-012** [odwyersoftware/mega.py#62]
File "D:\PYTHON\lib\shutil.py", line 827, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\comp\\AppData\\Local\\Temp\\megapy_3wlw70ao'

**Comment by alejandro0619** [comment]
Did you find how to solve it? I'm interested in finding a solution to this problem.

**Comment by ACE-012** [comment]
sorry for the late response,
yes i solved it
just remove a tabin the two lines in mega.nz 745,745  as mentioned in the image
![Uploading Screenshot 2021-09-23 185748.png…]()

**Comment by ACE-012** [comment]
sorry for the late response,
yes i solved it
just remove a tabin the two lines in mega.nz 745,745 as mentioned in the image
![Screenshot 2021-09-23 185748](https://user-images.githubusercontent.com/62414399/134515923-8dffa106-c061-4864-b692-59e7b168ba7e.png)

**Comment by alejandro0619** [comment]
> sorry for the late response,
> yes i solved it
> just remove a tab from the two lines in mega.py 745,745 as mentioned in the image
> ![Screenshot 2021-09-23 185748](https://user-images.githubusercontent.com/62414399/134515923-8dffa106-c061-4864-b692-59e7b168ba7e.png)

Thank you so much for taking the time to response this comment. It worked!
