### ISSUE TITLE
Cant login to account

### ISSUE THREAD

**Issue by ilarramendi** [odwyersoftware/mega.py#84]
Helo! Im trying to use this library but im getting this error when logging in:
`mega.errors.RequestError: ENOENT, Object (typically, node or user) not found`
My code is:
```
from mega import Mega
m = Mega().login('redacted','redacted')
```

**Comment by ZaneBrown** [comment]
When logging in to mega, it needs to be in the form of:
`m = mega.login(email, password)`
instead of:
`m = Mega().login(email, password)`

**Comment by ilarramendi** [comment]
Actually this:
```
m = Mega().login(email, password)
```
And this:
```
mega = Mega()
m = mega.login(email, password)
```
Are the equivalent for the login step, i just posted it like that for a minimal example.  
After posting this i uninstalled the library (and also python Mega library, not sure why i had that installed) and installed again and its working with the same syntax!
Probably a compatibility problem because they have the same name or something?  
Thanks for the reply anyway!
